# Source: https://github.com/per1234/.github/blob/main/workflow-templates/compile-examples-private.md
name: Compile Examples

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/compile-examples.ya?ml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/compile-examples.ya?ml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  workflow_dispatch:
  repository_dispatch:

env:
  UNIVERSAL_SKETCH_PATHS: |
        - examples/Barcode
        - examples/Keyboard
        - examples/KeyboardAndMouse
        - examples/Mouse
  SKETCHES_REPORTS_PATH: sketches-reports
  SKETCHES_REPORTS_ARTIFACT_NAME: sketches-reports

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:renesas_portenta:portenta_c33
            platforms: |
              - name: arduino:renesas_portenta
            artifact-name-suffix: arduino-renesas_portenta-portenta_c33

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          sketch-paths: |
            ${{ env.UNIVERSAL_SKETCH_PATHS }}
            ${{ matrix.board.additional-sketch-paths }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
